### ISSUE TITLE
about the depth information

### ISSUE THREAD

**Issue by jeffreyking23** [LizhenWangT/NormalGAN#2]
Hello, amazing work, really love it, because i don't have a kinect, can I use the result of sigle view depth estimation methods instead of kinectV2 depth?

**Comment by LizhenWangT** [comment]
Thank you for your interest on our work! We haven't test our method on depth estimation methods yet. But I think if you can generate high-quality predicted depth maps, NormalGAN might still work. Actually, FACSMILE and Moulding Humans shows the ability to generate full body from a single RGB image. However, it might be much more difficult to inference the invisible geometric details.
