### ISSUE TITLE
Orthographic mask in depth rectification network

### ISSUE THREAD

**Issue by RohanChacko** [LizhenWangT/NormalGAN#3]
Hi,
Interesting work. The supplementary section mentions that the front-view depth rectification network outputs a 1D rectified depth image and a 1D binary mask of the orthographic view. How does the mask help in learning depth image? Would I get the same results if I train the network without predicting the orthographic mask?

**Comment by LizhenWangT** [comment]
Thank you for your interest! As we can not directly get the orthographic mask from the input perspective RGBD images, I think it might be necessary to predict the orthographic mask. Moreover, the orthographic masks act as prior information of input images without background during the training of our discriminators. But if you train your images only in the perspective view, I think you  might generally get similar results.

**Comment by RohanChacko** [comment]
Thanks for the clarification!
